name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Update umbchvz.com
    steps:
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: "umbchvz.com"
        username: "www-data"
        password: ${{ secrets.WWW_DATA_PASSWORD }}
        script: "cd /var/www && git pull"
